### ISSUE TITLE
reenable PGP after fixing it to be less variable, error prone, unrecorded

### ISSUE THREAD

**Issue by zancas** [LeastAuthority/leastauthority.com#272]
I'm automating the process I go through after being notified of a PGP signup.

**Comment by daira** [comment]
Disabled. Leaving the ticket open in case we want to reenable it at some point.

**Comment by david415** [comment]
I don't think we should enable this feature again until we fix the more fundamental problems with this whole system such as:

- automated deployment of a new "leastauthority.com" site
- automated backups of customer data
- we need a better format for storing customer data

**Comment by david415** [comment]
...but of course if we were going to enable this feature we'd surely use Isis's python gnupg api... and seriously consider asking her to do it for money... since her work is very high quality and it would be extremely easy for her to complete albeit within a half hour since she's the domain expert on the abstraction she wrote. Not using her software to do this is definitely a mistake.

**Comment by Liz315** [comment]
Replaced by #465
