### ISSUE TITLE
unbitrot and document the process for deploying the blog

### ISSUE THREAD

**Issue by daira** [LeastAuthority/leastauthority.com#366]
As a workaround we currently have the rendered blog checked into the leastauthority.com repo, but this is not desirable.

**Comment by david415** [comment]
Currently we only deploy the blog static contents to a single webserver. When I deployed the test blog I just used scp to copy the blog_source repo to the remote machine. This is only really acceptable at our small scale... AND I don't see us planning for increasing our capacity to serve the blog to more and more users. Therefore might a simple approach like using "scp" be good enough for now until we must think about a "real" deployment system that scales well across many machines?

**Comment by david415** [comment]
btw I really hate Chef and Puppet; the whole "sysadmin" "devops" industry is full of software tools that promote ambient authority. In particular I would be inclined to try and avoid having one server control the rest of my servers.

**Comment by nathan-at-least** [comment]
The current approach of rendering into the sibling `leastauthority.com` repo is messy, *but*, it's easy to understand:

1. Edit blog until `rst2*` or the github rst rendering look right.
2. On the dev system, run `python ./render_blog.py`
3. On the dev system: view the rendering in `leastauthority.com` repo.
4. If satisfied, commit it (to a newly named branch?)
5. Now, do whatever the deployment process is for the website static content.

The reason I think this is good enough is the clear separation of concerns and modularity between 4 and 5. Instead, I would say improving step 5 is a higher priority. We need a good clean way to deploy static content upgrades.

There's a trick here, because some static content affects the "web app" site of things, and I feel that should be packages with the "web app" and deployed with it, as they are tightly coupled. Other static content, like the blog or many such files are independent of the web app logic, and it'd be nice to have a clear separation and a separate deployment process for them that doesn't require server restarts.

For static files deployment, I like this process, but I'm happy with anything else that's reasonable: the static content base directory is inside a git repository checkout, but underneath the root checkout (so that, eg .git is not reachable as static website content).  The live content lives on a branch named something appropriate, like "live-content".  The "to be published" content is on a branch which is never checked out locally with a name like "soon-to-be-live-content".  Deploying new static content is accomplished on the production/staging server with:

```bash
$ cd /path/to/static-content-checkout
$ git pull --ff-only soon-to-be-live-content
```

**Note:** This implies the ops engineer must ssh in and assume the correct account id.  Let's let ssh and the ops engineer handle that, and not any automation.

When we want to push new content, from a dev system, we update the ``soon-to-be-live-content`` branch appropriately, then use git push to push it to a website.  (This assumes the ops engineer can ssh directly to the website account...  We need another wrinkle if we want to allow ssh access only with per-person accounts which then sudo to access the website account.)

**Comment by daira** [comment]
This *should* be documented at https://github.com/LeastAuthority/LeastAuthoritarians/wiki/blog-deployment .

**Comment by Liz315** [comment]
Overcome by new site (coming).
