### ISSUE TITLE
Create good error handling for wormhole codes for other addresses

### ISSUE THREAD

**Issue by Liz315** [LeastAuthority/leastauthority.com#493]
Since we are hard-code an address for the Least Authority wormhole server, for now, we need to make sure the error messages are helpful if someone else tries to use Gridsync with a different wormhole server.

**Comment by crwood** [comment]
I'm not sure that I understand this issue. As it currently stands, it's not possible for Gridsync to connect to any wormhole server other than the one that's baked into the client (which, in this case, already is Least Authority's).

That said, maybe I'm missing (or forgetting) something here.. Can you or @exarkun clarify?

**Comment by exarkun** [comment]
I think what we discussed was having good error handling in GridSync if we choose to move the wormhole server or somehow re-deploy it in an incompatible way - error handling such that the user is informed that they basically need to upgrade GridSync.

We have wormhole.leastauthority.com now.  This is a single point of failure.  If a future version of magic wormhole can be set up in some kind of multi-node redundant configuration, perhaps we can still have this hostname pointing at it.  It's not clear that's the direction things will go, though.  Perhaps there will be some kind of DHT-based server and the client should connect to a hostname that's somehow derived from the code they presented.  Maybe the magic wormhole protocol will change in some other unpredictable, incompatible way.  Whatever happens, if old GridSynces are going to stop working with our deployment, we'll want a good user experience.

**Comment by crwood** [comment]
Yes, I recall those discussions. The core of the issue, however (which I should have expanded on above) is that Gridsync currently lacks any sort of extrospection or self-update mechanisms that would ultimately enable it to properly distinguish between a) failing to complete an invitation because the wormhole server is currently inaccessible and b) failing to complete an invitation because the wormhole server has moved or been re-deployed in an incompatible way. In other words, Gridsync can know _that_ the wormhole server is inaccessible, but it cannot know _why_ (and the question of "why", I think, is what needs to be satisfied in order to meaningfully distinguish between the two types of failures above -- or at least in order to be truthful in informing the user that they _need_ to upgrade).

That said, the way I see it, there are at least two ways of addressing this for now -- the easy way and the more involved way -- neither of which is fully satisfactory:

1) The easy way: if Gridsync can't connect to the wormhole server, it informs the user of this via an error message (as it already does) but with the added suggestion of "Please ensure that you are using the latest version" (or similar) and some easy means of directing them to the soon-to-be-created download page. This solution wouldn't convey that an update is _needed_ (since other factors could still be responsible for the failure) but it would at least help to nudge users in the right direction in the event that there actually is some incompatible change on the server-side and/or at the protocol level down the line.

2) The more involved way: Gridsync periodically queries some service (e.g., GitHub's Releases API) and informs the user of any new releases. Following [semver's](http://semver.org/) suggestion of using "major" numbers for backwards-incompatible changes, Gridsync could "know" (or at least have a higher degree of confidence) that an upgrade is _needed_ (vs. being merely _suggested_) and notify the user with an according sense of urgency. I don't like this solution for a myriad of privacy and security-related reasons (and would generally prefer to wait until a more robust self-update mechanism, e.g., [TUF](https://theupdateframework.github.io/), can be put into place) but this would at least provide a means of informing the user that there actually _is_ an (important, potentially backwards-incompatible) update instead of just guessing that there _may_ be one.

Personally, I'm content with the softer/less-accurate method of suggesting to users that they check for updates in the event of failure (and will go ahead and implement that for now) but I'd be interested in hearing more about what might constitute "good error handling" for this. I would also like to suggest that "good error handling," on a broader level, probably involves reducing the probability of errors occurring in the first place -- in this case, committing to keeping a potentially "legacy" wormhole server alive if or when those backwards-incompatible changes occur upstream.

**Comment by exarkun** [comment]
Reading the wormhole protocol docs, I saw this section about the initial message a server sends a client - the "welcome" message, including an "error" field.

Can we have GridSync do something sensible with the error field?  Then if we want to make an incompatible change to the wormhole server, we can leave behind a server that does nothing but respond with an error message of our choice.  It seems like that would be sufficient to convey the necessary information to users and avoids the heuristic approach of trying to guess what a connection failure might mean.

**Comment by crwood** [comment]
Okay, after delving further into the wormhole source code (and just as I was about to start writing a lower-level protocol handler!), I discovered that we can achieve the desired outcome relatively easily on both ends: the `wormhole-server` CLI already provides a `--signal-error` flag (under the `start` and `restart` sub-commands) that, when passed, will cause incoming clients to raise a `WelcomeError` (which I will have Gridsync interpret as "upgrade needed").

Making backwards-incompatible changes to our invite system in the future would thus entail simply keeping the old wormhole server running with `--signal-error`.

**Comment by meejah** [comment]
Another point I just thought of: there's really two protocols here, the 'wormhole' protocol and the 'what we do with the messages out of wormhole' protocol.

We should probably add a `"version": 0` to the JSON that we send as part of the second protocol, "just in case". I mean, we can "just add new keys" and it'll probably work fine, but ....

The second protocol is Very Simple right now: connect, and the "server"-side sends you a blob of JSON. Done. But it might be that in the future we want to do some back-and-forth stuff (e.g. client responds with some configuration information), so we could trigger new behavior like that with the version key too.

**Comment by exarkun** [comment]
> We should probably add a "version": 0 to the JSON that we send as part of the second protocol, "just in case". I mean, we can "just add new keys" and it'll probably work fine, but ....

:+1:

**Comment by crwood** [comment]
Good call. I've since added a `version` field to the [invite specification doc](https://github.com/gridsync/gridsync/blob/master/docs/invite.rst) that I've been maintaining but starting with a value of 1 instead of 0 in order to be more consistent with the versioning contained in the relay URL and appid (both of which are 1-indexed). I'll have Gridsync respond to any greater-than-1 value with an appropriate user-facing "upgrade needed" message.

In the meantime, I'm wondering whether the JSON blob should include a `type` field in addition to (or even in place of) the `version` field that would specify _what_ is being shared if only for the sake of providing additional context to clients of the future. Right now, for example, Gridsync's wormhole handling only processes/expects invitations to grids (and thus the `type` field might contain a value of `grid` -- or even `grid-v1` -- for now) but, in the future, we might want to support clients sharing other things through wormholes -- like magic-folder invites, single caps, full files/folders, etc. The reason I suggest an additional field for this is because In some cases -- such as inviting someone to join a magic-folder -- it might be preferable to also embed the grid connection information into the JSON blob so that the receiving party doesn't have to enter one invitation code to join the grid and then another, separate code immediately afterwards to join the magic-folder. In effect we could easily collapse what would normally be two separate invitations into one by sending out the information necessary to perform both tasks and then using the `type` field to determine the Right Thing to do with that information under the hood..

Of course, sharing is still a while off so we probably need not worry about any of this now but I figure it might be worth throwing out there for consideration anyway since extensibility is related to future-proofing (and a `type` field -- or something like it -- might provide an easy but flexible means of expanding upon wormhole-related functionality later on).

**Comment by exarkun** [comment]
> In the meantime, I'm wondering whether the JSON blob should include a type field in addition to (or even in place of) the version field that would specify what is being shared

I think that a `type` field will eventually make sense but I'd be inclined to leave it until we're actually ready to implement a feature that relies on it.  At that point, we can bump the version and change the rest of the schema however we want - and by doing it when we know about what we're using it for makes it more likely we'll get the details right.

**Comment by crwood** [comment]
Fair enough; we'll hold off on all that for now.

In the meantime, this Issue can (probably?) be closed: Gridsync will now show a user-facing error message (asking them to upgrade to the latest version) if either of the following conditions are met:

1. The wormhole server at `wormhole.leastauthority.com` is sending out a welcome error (i.e., the server is running with the `--signal-error` flag set).

2. A `version` field is present in the received JSON blob and has a value greater than 1.
