### ISSUE TITLE
add information to the website about what "wormhole codes" are

### ISSUE THREAD

**Issue by exarkun** [LeastAuthority/leastauthority.com#579]
The wormhole-based post-signup page offers the user a wormhole code and encourages them to use it with gridsync to get started with their subscription.  There's future plans to explain how "tahoe invite" can be used instead of gridsync, too.

But "wormhole codes" are obscure and we can rely on almost none of our users having ever encountered them before.  Add a page that explains what they are, what their security properties are, why we use them, and any practical details (such as expiration, failure to claim / retry, etc) the user may need to know about when using them to complete the signup process.

**Comment by crwood** [comment]
Here's a first stab at explaining (geared toward non-technical end-users):

https://github.com/gridsync/gridsync/blob/master/docs/invite-codes.md

Note that I'm using "invite code" instead of "wormhole code" throughout (since the former expresses a good degree of purpose/functionality to the user, whereas the latter does not and begs for further clarification). Accordingly, I'd argue that we should altogether avoid using the term "wormhole code" in every place that's user-facing (and use "invite code" instead).

**Comment by exarkun** [comment]
I think this was fixed by #583
